### PR TITLE
Upgrade lodash to use the same version as core

### PR DESCRIPTION
**Pull request by hamnis**
changed amd path to be correct with upgrade.

I was unable to run tests :( and I dont understand how to fix them.

### CODE REVIEW

**Comment by hamnis** [comment]
This fixes #25

**Comment by rrees** [comment]
It looks as if the tests are failing, possibly due to a similar reason of a browser behaviour change in Chrome as we've recently seen in the `scribe-plugin-smart-lists`.

I'll have to investigate a bit further.

**Comment by hamnis** [comment]
Any progress?

**Comment by rrees** [comment]
I understand the problem better but I haven't been able to solve it. I'm going to make an effort to try and get a stablised version of the plugin in out with some disabled tests. It will also fix the Lodash issue.

Beyond that I'm not sure how to fix the issues which seem to be the way Chrome is representing the content.

**Pull request closed without merging**
